# .github/workflows/staging.yml
name: Deploy to Staging

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_DEL_SERVIDOR }}
        username: ${{ secrets.USUARIO_SERVIDOR }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/lemp-sites/facundo_oyola/staging
          git pull origin develop